---
- name: Configure fish
  block:
    - name: Ensure config folder exists
      ansible.builtin.file:
        path: "{{ fish_config_dir }}"
        state: directory
        mode: "0750"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Add fish config file
      ansible.builtin.template:
        src: "{{ role_path }}/templates/config.fish.j2"
        dest: "{{ fish_config_file }}"
        mode: "0600"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Ensure functions folder exists
      ansible.builtin.file:
        path: "{{ fish_functions_dir }}"
        state: directory
        mode: "0750"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Add fish functions
      ansible.builtin.copy:
        src: "files/functions/"
        dest: "{{ fish_functions_dir }}"
        mode: 0750
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
