---
- name: Check installed fish version
  block:
    - name: Get installed fish version
      ansible.builtin.command:
        cmd: "fish --version"
      environment:
        PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
      ignore_errors: true
      changed_when: false
      failed_when: false
      register: fish_installed_version_cmd

    - name: Extract only the version into a variable
      ansible.builtin.set_fact:
        fish_installed_version: "{{ fish_installed_version_cmd.stdout | regex_replace('^.*?([\\d\\.]{2,}).*$', '\\1') }}"

    - name: Debug installed fish version
      ansible.builtin.debug:
        var: fish_installed_version
